### ISSUE TITLE
CustomAreas

### ISSUE THREAD

**Issue by radiomann** [luca28pet/CustomAreas#1]
Hi This sounds a great plugin and have downloaded it, i want to protect certain builds on my world but not really sure what i do? I am new to plugins so any help would be very greatful.

Many thanks

**Comment by ecoron** [comment]
its very easy. think its an invisable cube around.
go to the bottom right corner and type 
/ca pos1 
then go diagonal to the top left corner and type 
/ca pos2

finally  type
/ca create

and your build is protected. 
there are several more commands you can find in the documentation.

**Comment by robske110** [comment]
How about closing this issue?
