### ISSUE TITLE
How to download the plugin (.phar)?

### ISSUE THREAD

**Issue by MCITGAMER11** [luca28pet/CustomAreas#5]
Hello!!This plugin is very nice but i do not know how to download the .phar of this plugin.
Also, Will tjis Plugin work with MCPE 1.0.5 and Can you upload this to the PocketMine Forums Plugins?

**Comment by Matthieu05** [comment]
https://poggit.pmmp.io/ci/luca28pet/CustomAreas/CustomAreas
